linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Check for issues in printf/println statements, etc.
    - staticcheck    # Finds common bug patterns
    - gofmt          # Enforces formatting standards

issues:
  exclude-files:
    - .*_test.go   # Example to exclude test files from linting, if desired
