linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Run Go's vet tool
    - staticcheck    # Static analysis for potential bugs
    - gofmt          # Ensures proper formatting
  disable:
    - gocyclo        # Optional: Disable cyclomatic complexity check

run:
  timeout: 5m
  skip-files:
    - .*_test.go
